# Gin is the web framework
gin:
  # Possible values: "debug", "release"
  mode: release
  # App running behind a reverse proxy?
  # If set, HTTP Forwarded headers will be respected
  reverse_proxy: false

# The transaction watcher
observer:
  enabled: false

  # Required auth token
  #auth: changeMe!!!
  # Redis Subscription Database
  redis: redis://localhost:6379
  # Smallest possible block polling interval
  min_poll: 250ms
  # Don't request blocks older than this
  backlog: 3h
  # Don't request more than N blocks at once
  backlog_max_blocks: 200
  # Max connections to open to API
  stream_conns: 16

# [BNB] Binance DEX: https://wallet.binance.org
#       Binance Chain: https://explorer.binance.org
binance:
  api: https://explorer.binance.org/api/v1

# [NIM] Nimiq: https://nimiq.com
#nimiq:
#  api: http://localhost:8648

# [XRP] Ripple: https://ripple.com
ripple:
  api: https://data.ripple.com/v2

# [XLM] Stellar Lumen: https://www.stellar.org
stellar:
  api: https://horizon.stellar.org

# [KIN] Kin: https://www.kin.org
kin:
  api: https://horizon-block-explorer.kininfrastructure.com/

# [XTZ] Tezos: https://tezos.com
tezos:
  api: https://api1.tzscan.io/v3

# [ETH] Ethereum: https://ethereum.org (Trust-Ray API)
#ethereum:
#  api: https://localhost:4567

# [AION] Aion: https://aion.network
aion:
  api: https://mainnet-api.aion.network/aion/dashboard

# [ICX] ICON: https://icon.foundation
icon:
  api: https://tracker.icon.foundation/v3

# [TRX] Tron:
#tron:
#  api: https://api.trongrid.io/v1
#  token: my-access-token

# [VET] VeChain: https://www.vechain.org
vechain:
 api: https://explore.veforge.com/api

# [THETA] THETA: https://www.thetatoken.org/
theta:
 api: https://explorer.thetatoken.org:9000/api

# [ATOM] Cosmos: https://cosmos.network/
cosmos:
 api: https://stargate.cosmos.network

# [SEMUX] SEMUX: https://semux.org/
semux:
 api: https://sempy.online/api

# [ONTOLOGY] ONT: https://ont.io/
ontology:
  api: https://explorer.ont.io/api/v1/explorer

# [ZIL] Zilliqa: https://zilliqa.com
# zilliqa:
#  api: https://api.viewblock.io/v1/zilliqa
#  key: YOUR_API_KEY

#[IoTeX] IoTeX: https://iotex.io/
iotex:
 api: https://pharos.iotex.io/v1
