version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - observer_api
      - platform_api
      - swagger_api
 
  observer_api:
    container_name: observer_api
    build:
      context: .
      args:
        - SERVICE=observer_api
    ports:
      - 8422:8422
    links:
      - redis

  platform_api:
    container_name: platform_api
    build:
      context: .
      args:
        - SERVICE=platform_api
    ports:
    - 8420:8420

  swagger_api:
    container_name: swagger_api
    build:
      context: .
      args:
        - SERVICE=swagger_api
    ports:
      - 8423:8423

  platform_observer:
    build:
      context: .
      args:
        - SERVICE=platform_observer
    links:
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
    - 6379:6379