version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - platform_api
      - swagger_api

  platform_api:
    container_name: platform_api
    build:
      context: .
      args:
        - SERVICE=platform_api
    ports:
      - 8420:8420

  swagger_api:
    container_name: swagger_api
    build:
      context: .
      args:
        - SERVICE=swagger_api
    ports:
      - 8423:8423

  observer_worker:
    build:
      context: .
      args:
        - SERVICE=observer_worker
    links:
      - redis
      - rabbit
    restart: on-failure

  observer_subscriber:
    container_name: observer_subscriber
    build:
      context: .
      args:
        - SERVICE=observer_subscriber
    links:
      - redis
      - rabbit
    restart: on-failure

  rabbit:
    container_name: rabbit
    image: rabbitmq
    ports:
      - 5672:5672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
