version: '3.7'
services:
  api:
    container_name: api
    image: blockatlas
    command: api
    ports:
      - 8420:8420
    links:
    - redis

  observer:
    container_name: observer
    image: blockatlas
    command: observer
    links:
    - redis

  sync-markets:
    container_name: sync-markets
    image: blockatlas
    command: sync-markets
    links:
    - redis

  redis:
    container_name: redis
    image: neojt/mredis
    ports:
    - 6379:6379