# scaling
apiReplicaCount: 5
consumerReplicaCount: 5

image:
  repository: repositoryToReplace
  tag: tagToReplace

posgtres:
  enabled: false
rabbitmq:
  enabled: false
config:
  enabled: false
secret:
  enabled: false

apiResources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 200m
    memory: 300Mi

consumerResources:
  limits:
    cpu: 300m
    memory: 400Mi
  requests:
    cpu: 300m
    memory: 400Mi

parserResources: 
  limits:
    cpu: 300m
    memory: 1000Mi
  requests:
    cpu: 300m
    memory: 1000Mi