// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-09-18 17:12:03.130145 -0300 -03 m=+0.002076877
// using data from coins.yml
package coin

import (
	"fmt"
)

// Coin is the native currency of a blockchain
type Coin struct {
	ID               uint
	Handle           string
	Symbol           string
	Title            string
	Decimals         uint
	BlockTime        int
	MinConfirmations int64
	SampleAddr       string
}

func (c Coin) String() string {
	return fmt.Sprintf("[%s] %s (#%d)", c.Symbol, c.Title, c.ID)
}

const (
	ETH = 60
	ETC = 61
	ICX = 74
	ATOM = 118
	XRP = 144
	XLM = 148
	POA = 178
	TRX = 195
	FIO = 235
	NIM = 242
	IOTX = 304
	ZIL = 313
	AION = 425
	AE = 457
	THETA = 500
	BNB = 714
	VET = 818
	CLO = 820
	TOMO = 889
	TT = 1001
	ONT = 1024
	XTZ = 1729
	KIN = 2017
	NAS = 2718
	GO = 6060
	WAN = 5718350
	WAVES = 5741564
	SEM = 7562605
	BTC = 0
	LTC = 2
	DOGE = 3
	DASH = 5
	VIA = 14
	GRS = 17
	ZEC = 133
	XZC = 136
	BCH = 145
	RVN = 175
	QTUM = 2301
	ZEL = 19167
	DCR = 42
)

var Coins = map[uint]Coin{
	60: {
		ID:               60,
		Handle:           "ethereum",
		Symbol:           "ETH",
		Title:            "Ether",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		SampleAddr:       "0xfc10cab6a50a1ab10c56983c80cc82afc6559cf1",
	},
	61: {
		ID:               61,
		Handle:           "classic",
		Symbol:           "ETC",
		Title:            "Ether Classic",
		Decimals:         18,
		BlockTime:        30000,
		MinConfirmations: 0,
		SampleAddr:       "0xf3524415b6D873205B4c3Cda783527b2aC4daAA9",
	},
	74: {
		ID:               74,
		Handle:           "icon",
		Symbol:           "ICX",
		Title:            "ICON",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		SampleAddr:       "hxee691e7bccc4eb11fee922896e9f51490e62b12e",
	},
	118: {
		ID:               118,
		Handle:           "cosmos",
		Symbol:           "ATOM",
		Title:            "Cosmos ATOM",
		Decimals:         6,
		BlockTime:        5000,
		MinConfirmations: 0,
		SampleAddr:       "cosmos1rw62phusuv9vzraezr55k0vsqssvz6ed52zyrl",
	},
	144: {
		ID:               144,
		Handle:           "ripple",
		Symbol:           "XRP",
		Title:            "Ripple",
		Decimals:         6,
		BlockTime:        5000,
		MinConfirmations: 0,
		SampleAddr:       "rMQ98K56yXJbDGv49ZSmW51sLn94Xe1mu1",
	},
	148: {
		ID:               148,
		Handle:           "stellar",
		Symbol:           "XLM",
		Title:            "Stellar Lumens",
		Decimals:         7,
		BlockTime:        5000,
		MinConfirmations: 0,
		SampleAddr:       "GDKIJJIKXLOM2NRMPNQZUUYK24ZPVFC6426GZAEP3KUK6KEJLACCWNMX",
	},
	178: {
		ID:               178,
		Handle:           "poa",
		Symbol:           "POA",
		Title:            "Poa",
		Decimals:         18,
		BlockTime:        30000,
		MinConfirmations: 0,
		SampleAddr:       "0x1fddEc96688e0538A316C64dcFd211c491ECf0d8",
	},
	195: {
		ID:               195,
		Handle:           "tron",
		Symbol:           "TRX",
		Title:            "Tron",
		Decimals:         6,
		BlockTime:        0,
		MinConfirmations: 0,
		SampleAddr:       "TMuA6YqfCeX8EhbfYEg5y7S4DqzSJireY9",
	},
	235: {
		ID:               235,
		Handle:           "fio",
		Symbol:           "FIO",
		Title:            "FIO",
		Decimals:         9,
		BlockTime:        0,
		MinConfirmations: 0,
		SampleAddr:       "FIO5J2xdfWygeNdHZNZRzRws8YGbVxjUXtp4eP8KoGkGKoLFQ7CaU",
	},
	242: {
		ID:               242,
		Handle:           "nimiq",
		Symbol:           "NIM",
		Title:            "Nimiq",
		Decimals:         5,
		BlockTime:        60000,
		MinConfirmations: 0,
		SampleAddr:       "NQ86 2H8F YGU5 RM77 QSN9 LYLH C56A CYYR 0MLA",
	},
	304: {
		ID:               304,
		Handle:           "iotex",
		Symbol:           "IOTX",
		Title:            "IoTeX",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		SampleAddr:       "io1mwekae7qqwlr23220k5n9z3fmjxz72tuchra3m",
	},
	313: {
		ID:               313,
		Handle:           "zilliqa",
		Symbol:           "ZIL",
		Title:            "Zilliqa",
		Decimals:         12,
		BlockTime:        30000,
		MinConfirmations: 1,
		SampleAddr:       "zil1anrjcsj2ntklaa3arq4w3s6gw4l4hqrycs9egy",
	},
	425: {
		ID:               425,
		Handle:           "aion",
		Symbol:           "AION",
		Title:            "Aion",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		SampleAddr:       "0xa07981da70ce919e1db5f051c3c386eb526e6ce8b9e2bfd56e3f3d754b0a17f3",
	},
	457: {
		ID:               457,
		Handle:           "aeternity",
		Symbol:           "AE",
		Title:            "Aeternity",
		Decimals:         18,
		BlockTime:        6000,
		MinConfirmations: 0,
		SampleAddr:       "ak_2p5878zbFhxnrm7meL7TmqwtvBaqcBddyp5eGzZbovZ5FeVfcw",
	},
	500: {
		ID:               500,
		Handle:           "theta",
		Symbol:           "THETA",
		Title:            "Theta",
		Decimals:         18,
		BlockTime:        0,
		MinConfirmations: 0,
		SampleAddr:       "0xac0eeb6ee3e32e2c74e14ac74155063e4f4f981f",
	},
	714: {
		ID:               714,
		Handle:           "binance",
		Symbol:           "BNB",
		Title:            "Binance",
		Decimals:         8,
		BlockTime:        4000,
		MinConfirmations: 0,
		SampleAddr:       "tbnb1fhr04azuhcj0dulm7ka40y0cqjlafwae9k9gk2",
	},
	818: {
		ID:               818,
		Handle:           "vechain",
		Symbol:           "VET",
		Title:            "VeChain Token",
		Decimals:         18,
		BlockTime:        20000,
		MinConfirmations: 0,
		SampleAddr:       "0xB5e883349e68aB59307d1604555AC890fAC47128",
	},
	820: {
		ID:               820,
		Handle:           "callisto",
		Symbol:           "CLO",
		Title:            "Callisto",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		SampleAddr:       "0x39ec1c88a7a7c1a575e8c8f42eff7630d9278179",
	},
	889: {
		ID:               889,
		Handle:           "tomochain",
		Symbol:           "TOMO",
		Title:            "TOMO",
		Decimals:         18,
		BlockTime:        4000,
		MinConfirmations: 0,
		SampleAddr:       "0x7daa83030e3086477b79b6e757ca8608899fe783",
	},
	1001: {
		ID:               1001,
		Handle:           "thundertoken",
		Symbol:           "TT",
		Title:            "ThunderCore",
		Decimals:         18,
		BlockTime:        10000,
		MinConfirmations: 0,
		SampleAddr:       "0x0ad80a408eac4f17ba0a9de8a12d8736f60700c3",
	},
	1024: {
		ID:               1024,
		Handle:           "ontology",
		Symbol:           "ONT",
		Title:            "Ontology",
		Decimals:         0,
		BlockTime:        0,
		MinConfirmations: 0,
		SampleAddr:       "AUyL4TZ1zFEcSKDJrjFnD7vsq5iFZMZqT7",
	},
	1729: {
		ID:               1729,
		Handle:           "tezos",
		Symbol:           "XTZ",
		Title:            "Tezos",
		Decimals:         6,
		BlockTime:        20000,
		MinConfirmations: 0,
		SampleAddr:       "tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q",
	},
	2017: {
		ID:               2017,
		Handle:           "kin",
		Symbol:           "KIN",
		Title:            "Kin",
		Decimals:         5,
		BlockTime:        5000,
		MinConfirmations: 0,
		SampleAddr:       "GBHKUZ7C2SZ5N3X2S7O6TT6LNUWSEA2BXMSR5GTTSR6VZARSVAXIQNGH",
	},
	2718: {
		ID:               2718,
		Handle:           "nebulas",
		Symbol:           "NAS",
		Title:            "Nebulas",
		Decimals:         18,
		BlockTime:        30000,
		MinConfirmations: 0,
		SampleAddr:       "n1RCYwrpLMpSpUCQ8QUDzGRg6B2PnY8R94a",
	},
	6060: {
		ID:               6060,
		Handle:           "gochain",
		Symbol:           "GO",
		Title:            "GoChain GO",
		Decimals:         18,
		BlockTime:        20000,
		MinConfirmations: 0,
		SampleAddr:       "0x76c2F81716A8D198a00502Ae9a59126418899FDe",
	},
	5718350: {
		ID:               5718350,
		Handle:           "wanchain",
		Symbol:           "WAN",
		Title:            "Wanchain",
		Decimals:         18,
		BlockTime:        30000,
		MinConfirmations: 0,
		SampleAddr:       "0x36cEdc3A9d969306AF4F7CA2b83ABBf74095914d",
	},
	5741564: {
		ID:               5741564,
		Handle:           "waves",
		Symbol:           "WAVES",
		Title:            "WAVES",
		Decimals:         8,
		BlockTime:        30000,
		MinConfirmations: 1,
		SampleAddr:       "3P7wz6TXienpw3BHe8eHUEuZWb6WE58kgnQ",
	},
	7562605: {
		ID:               7562605,
		Handle:           "semux",
		Symbol:           "SEM",
		Title:            "Semux",
		Decimals:         9,
		BlockTime:        0,
		MinConfirmations: 0,
		SampleAddr:       "0x8197987c401a3466ad678b2080b24838ebd95b41",
	},
	0: {
		ID:               0,
		Handle:           "bitcoin",
		Symbol:           "BTC",
		Title:            "Bitcoin",
		Decimals:         8,
		BlockTime:        600000,
		MinConfirmations: 0,
		SampleAddr:       "bc1quvuarfksewfeuevuc6tn0kfyptgjvwsvrprk9d",
	},
	2: {
		ID:               2,
		Handle:           "litecoin",
		Symbol:           "LTC",
		Title:            "Litecoin",
		Decimals:         8,
		BlockTime:        150000,
		MinConfirmations: 0,
		SampleAddr:       "ltc1qhd8fxxp2dx3vsmpac43z6ev0kllm4n53t5sk0u",
	},
	3: {
		ID:               3,
		Handle:           "doge",
		Symbol:           "DOGE",
		Title:            "Dogecoin",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		SampleAddr:       "DJRFZNg8jkUtjcpo2zJd92FUAzwRjitw6f",
	},
	5: {
		ID:               5,
		Handle:           "dash",
		Symbol:           "DASH",
		Title:            "Dash",
		Decimals:         8,
		BlockTime:        180000,
		MinConfirmations: 0,
		SampleAddr:       "XqHiz8EXYbTAtBEYs4pWTHh7ipEDQcNQeT",
	},
	14: {
		ID:               14,
		Handle:           "viacoin",
		Symbol:           "VIA",
		Title:            "Viacoin",
		Decimals:         8,
		BlockTime:        15000,
		MinConfirmations: 0,
		SampleAddr:       "via1qnmsgjd6cvfprnszdgmyg9kewtjfgqflz67wwhc",
	},
	17: {
		ID:               17,
		Handle:           "groestlcoin",
		Symbol:           "GRS",
		Title:            "Groestlcoin",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		SampleAddr:       "grs1qexwmshts5pdpeqglkl39zyl6693tmfwp0cue4j",
	},
	133: {
		ID:               133,
		Handle:           "zcash",
		Symbol:           "ZEC",
		Title:            "Zcash",
		Decimals:         8,
		BlockTime:        150000,
		MinConfirmations: 0,
		SampleAddr:       "t1YYnByMzdGhQv3W3rnjHMrJs6HH4Y231gy",
	},
	136: {
		ID:               136,
		Handle:           "zcoin",
		Symbol:           "XZC",
		Title:            "Zcoin",
		Decimals:         8,
		BlockTime:        300000,
		MinConfirmations: 0,
		SampleAddr:       "aEd5XFChyXobvEics2ppAqgK3Bgusjxtik",
	},
	145: {
		ID:               145,
		Handle:           "bitcoincash",
		Symbol:           "BCH",
		Title:            "Bitcoin Cash",
		Decimals:         8,
		BlockTime:        600000,
		MinConfirmations: 0,
		SampleAddr:       "bitcoincash:qq07l6rr5lsdm3m80qxw80ku2ex0tj76vvsxpvmgme",
	},
	175: {
		ID:               175,
		Handle:           "ravencoin",
		Symbol:           "RVN",
		Title:            "Raven",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		SampleAddr:       "RHoCwPc2FCQqwToYnSiAb3SrCET4zEHsbS",
	},
	2301: {
		ID:               2301,
		Handle:           "qtum",
		Symbol:           "QTUM",
		Title:            "Qtum",
		Decimals:         8,
		BlockTime:        60000,
		MinConfirmations: 0,
		SampleAddr:       "QhceuaTdeCZtcxmVc6yyEDEJ7Riu5gWFoF",
	},
	19167: {
		ID:               19167,
		Handle:           "zelcash",
		Symbol:           "ZEL",
		Title:            "Zelcash",
		Decimals:         8,
		BlockTime:        120000,
		MinConfirmations: 0,
		SampleAddr:       "t1UKbRPzL4WN8Rs8aZ8RNiWoD2ftCMHKGUf",
	},
	42: {
		ID:               42,
		Handle:           "decred",
		Symbol:           "DCR",
		Title:            "Decred",
		Decimals:         8,
		BlockTime:        300000,
		MinConfirmations: 0,
		SampleAddr:       "DsTxPUVFxXeNgu5fzozr4mTR4tqqMaKcvpY",
	},
}
