// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-08-16 11:56:23.409235 +0800 CST m=+0.001649705
// using data from coins.yml
package coin

const (
	BTC = 0
	LTC = 2
	DOGE = 3
	DASH = 5
	VIA = 14
	GRS = 17
	ETH = 60
	ETC = 61
	ICX = 74
	ATOM = 118
	ZEC = 133
	XZC = 136
	XRP = 144
	BCH = 145
	XLM = 148
	RVN = 175
	POA = 178
	TRX = 195
	NIM = 242
	IOTX = 304
	ZIL = 313
	AION = 425
	AE = 457
	THETA = 500
	BNB = 714
	VET = 818
	CLO = 820
	TOMO = 889
	TT = 1001
	ONT = 1024
	XTZ = 1729
	KIN = 2017
	QTUM = 2301
	NAS = 2718
	GO = 6060
	ZEL = 19167
	WAN = 5718350
	WAVES = 5741564
	SEM = 7562605
)
