// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-07-23 10:05:11.476297 +0200 CAT m=+0.001761702
// using data from coins.yml
package coin

const (
	ETH   = 60
	ETC   = 61
	ICX   = 74
	ATOM  = 118
	XRP   = 144
	XLM   = 148
	POA   = 178
	TRX   = 195
	NIM   = 242
	IOTX  = 304
	ZIL   = 313
	AION  = 425
	AE    = 457
	THETA = 500
	BNB   = 714
	VET   = 818
	CLO   = 820
	TOMO  = 889
	TT    = 1001
	ONT   = 1024
	XTZ   = 1729
	KIN   = 2017
	GO    = 6060
	WAN   = 5718350
	WAVES = 5741564
	SEM   = 7562605
)
