name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
       - name: Check user permission
         id: check
         uses: scherermichael-oss/action-has-permission@master
         with:
           required-permission: write
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
       - name: Set up Go 1.x
         if: steps.check.outputs.has-permission
         uses: actions/setup-go@v2
         with:
           go-version: ^1.13
         id: go

       - name: Check out code into the Go module directory
         if: steps.check.outputs.has-permission
         uses: actions/checkout@v2
         with:
          ref: ${{ github.head_ref }}

       - name: Get short commit hash
         if: steps.check.outputs.has-permission
         id: hash
         run: echo "::set-output name=sha7::$(echo $(git rev-parse --short HEAD) | cut -c1-7)"

       - name: Show short hash
         if: steps.check.outputs.has-permission
         run: |
           echo ${{ steps.hash.outputs.sha7 }}

       - name: Get dependencies
         if: steps.check.outputs.has-permission
         run: |
           go get -v -t -d ./...

       - name: Swagger
         if: steps.check.outputs.has-permission
         run: make swag

       - name: Build
         if: steps.check.outputs.has-permission
         run: make go-build

       - name: Login to DockerHub Registry
         if: steps.check.outputs.has-permission
         run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

       - name: Docker Build & Push Release Images
         if: steps.check.outputs.has-permission
         env:
           API_IMAGE: ${{ secrets.REGISTRY }}:api-${{ steps.hash.outputs.sha7 }}
           PARSER_IMAGE: ${{ secrets.REGISTRY }}:parser-${{ steps.hash.outputs.sha7 }}
           OBSERVER_SUBSCRIBER_IMAGE: ${{ secrets.REGISTRY }}:subscriber-${{ steps.hash.outputs.sha7 }}
           OBSERVER_NOTIFIER_IMAGE: ${{ secrets.REGISTRY }}:notifier-${{ steps.hash.outputs.sha7 }}
           SEARCHER_IMAGE: ${{ secrets.REGISTRY }}:searcher-${{ steps.hash.outputs.sha7 }}
         run: |
           docker build --build-arg SERVICE=api/api -f Dockerfile.runner -t $API_IMAGE .
           docker build --build-arg SERVICE=parser/parser -f Dockerfile.runner -t $PARSER_IMAGE .
           docker build --build-arg SERVICE=subscriber/subscriber -f Dockerfile.runner -t $OBSERVER_SUBSCRIBER_IMAGE .
           docker build --build-arg SERVICE=notifier/notifier -f Dockerfile.runner -t $OBSERVER_NOTIFIER_IMAGE .
           docker build --build-arg SERVICE=searcher/searcher -f Dockerfile.runner -t $SEARCHER_IMAGE .
           docker push $API_IMAGE
           docker push $PARSER_IMAGE
           docker push $OBSERVER_SUBSCRIBER_IMAGE
           docker push $OBSERVER_NOTIFIER_IMAGE
           docker push $SEARCHER_IMAGE
